### PR TITLE
[Ready for Review] French - Wai-InvolveUsersEval

### PR DESCRIPTION
**Pull request by remibetin**
From Soahmed2031 #9

### CODE REVIEW

**Comment by remibetin** [comment]
@slhenry I added the caution id (as agreed in #12). 

For some reasons, it appears the double brackets you've added were already there in the French version. Can you tell me why and when we should use double brackets rather than single brackets ?

**Comment by shawna-slh** [comment]
> For some reasons, it appears the double brackets you've added were already there in the French version. Can you tell me why and when we should use double brackets rather than single brackets ?

Ah, yes.

Why they were in the French version: I assume because they were erroneously changed to single brackets after the translation fork was made.

When to use single and double: See updated [documentation of links and brackets](https://github.com/w3c/wai-resource-template/blob/master/content/index.md#heading-level-2). I added a link to that in the [Translation Instructions](https://www.w3.org/wiki/WAI/Translation_Instructions#Important_Translation_Guidance).

fyi, This was one of the things that changed, so some may not be correct.

**Comment by remibetin** [comment]
@shawna-slh What are the next steps for this PR ?

**Comment by shawna-slh** [comment]
Hi @remibetin
We should also provide translation of the VTT file.
https://github.com/w3c/wai-InvolveUsersEval/blob/master/content-images/wai-InvolveUsersEval/involving-users-cc.vtt
The text should be the same as in the first column of the transcript table.
I'll see if Tatiana or Flora want to do that. :-)

**Comment by shawna-slh** [comment]
Published! I did a separate branch https://github.com/w3c/wai-InvolveUsersEval/pull/19 so I could test the added vtt

**Pull request closed without merging**
